spring: 
  datasource: 
    url: jdbc:postgresql://postgresaws.csxsnrlrv8ur.sa-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: vigueraws
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      generate-ddl: true
    show-sql: true